# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: AzureCLI@2
  displayName: 'install az cli'
  inputs:
    azureSubscription: 'az-res-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az extension add -n azure-cli-ml'
- task: AzureCLI@2
  inputs:
    azureSubscription: 'az-res-conn'
    scriptType: 'bash'
    scriptLocation: 'inlineScript'
    inlineScript: 'az ml workspace create -g $(azureml.resourceGroup) -w $(azureml.workspaceName) -l $(azureml.location) --exist-ok --yes'

    